-- CreateTable
CREATE TABLE "Session" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "rawIdea" TEXT NOT NULL,
    "category" TEXT,
    "status" TEXT NOT NULL DEFAULT 'active',
    "currentStage" TEXT NOT NULL DEFAULT 'intake',
    "questionBudget" INTEGER NOT NULL DEFAULT 5,
    "clarityScore" INTEGER NOT NULL DEFAULT 18,
    "extractedProblem" TEXT,
    "extractedCustomer" TEXT,
    "extractedSolution" TEXT,
    "ideaSummary" TEXT,
    "targetUser" TEXT,
    "problem" TEXT,
    "solution" TEXT,
    "assumptions" TEXT NOT NULL DEFAULT '[]',
    "resolvedAssumptions" TEXT NOT NULL DEFAULT '[]',
    "risks" TEXT NOT NULL DEFAULT '[]',
    "unknowns" TEXT NOT NULL DEFAULT '[]',
    "evidenceFor" TEXT NOT NULL DEFAULT '[]',
    "evidenceAgainst" TEXT NOT NULL DEFAULT '[]',
    "marketPatterns" TEXT NOT NULL DEFAULT '[]',
    "questionsAsked" TEXT NOT NULL DEFAULT '[]',
    "answers" TEXT NOT NULL DEFAULT '[]',
    "conversation" TEXT NOT NULL DEFAULT '[]',
    "conceptBrief" TEXT,
    "logicOnlyMode" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
